### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by jiangxuhui** [JuanWoo/zhihuDaily#4]
另外，如何打包运行？

**Comment by JuanWoo** [comment]
在准备中，可以先临时用其他作者的网站替代。https://kanzhihu.pro/

**Comment by JuanWoo** [comment]
知乎恢复境外访问无望，已更新项目，有需要者可本地运行。

**Comment by JuanWoo** [comment]
本地化版本已经更新到github，按github上我写的说明就可以本地化运行了

jiangxuhui ***@***.***> 于2022年9月27日周二 09:35写道：
