### ISSUE TITLE
在“本地化运行-4.”时遇到一个问题

### ISSUE THREAD

**Issue by jogGUY** [JuanWoo/zhihuDaily#6]
![Windows 7 x64-2022-12-06-10-26-42](https://user-images.githubusercontent.com/108516858/205794708-05d5cb65-0d53-4c04-a69c-652dfa030358.png)
这是需要自己写配置什么的么？(┬┬﹏┬┬)

**Comment by JuanWoo** [comment]
是因为所在目录Program Files名中间有空格，解决方法有三个，任选其一：
1、把ZhihuDaily挪到不带空格的目录
2、用文本编辑器修改start.bat，第28行两个路径加上双引号，改成这个 set CP="%APP_BASE_PATH%config";"%APP_BASE_PATH%lib\*"
3、下载今天我更新后的版本

**Comment by jogGUY** [comment]
完美解决👍
另外想多问一嘴，这个项目可能实现局域网内访问么？( •̀ ω •́ )✧

**Comment by JuanWoo** [comment]
可以，局域网其他机器访问，就是在浏览器地址栏输入运行程序机器的IP地址。
